// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -70);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -33);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 2);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);

    ui_Label_name = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_name, -79);
    lv_obj_set_y(ui_Label_name, -110);
    lv_obj_set_align(ui_Label_name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_name, "301");

    ui_Label_battery = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label_battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_battery, 17);
    lv_obj_set_y(ui_Label_battery, -112);
    lv_obj_set_align(ui_Label_battery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_battery, "battery");

    ui_Bar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar1, 21, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 50);
    lv_obj_set_height(ui_Bar1, 15);
    lv_obj_set_x(ui_Bar1, 78);
    lv_obj_set_y(ui_Bar1, -112);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    ui_Chart1 = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Chart1, 200);
    lv_obj_set_height(ui_Chart1, 90);
    lv_obj_set_x(ui_Chart1, 0);
    lv_obj_set_y(ui_Chart1, 68);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);




}
